export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_ALL_COURSE = "GET_ALL_COURSE";
export const GET_COURSE_SELECTION = "GET_COURSE_SELECTION";
export const UPDATE_SELECTION = "UPDATE_SELECTION";
export const SAVE_SELECTION = "SAVE_SELECTION";
